logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: WARN
    com.infopulse: DEBUG
    javax.management.remote.rmi: WARN

  # Se estiver faltando, adicione para garantir que os logs vão para o console
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n' # Formato de saída no console

  file:
    name: application-dev.log # Se quiser também salvar em arquivo

  # Se não estiver usando logstash, desative para evitar ruídos
  logstash:
    enabled: false

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/infopulse
    username: postgres
    password: postgre123
    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: smtp.gmail.com
    port: 587
    username: abrahamlica451@gmail.com
    password: godaboveall123@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8080

# JHipster specific properties

jhipster:
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: MTdhMTNiYjE2N2VlZWIwYmIxNTZiMWJkMGQ0ZGNlZjE5ZDU3MDdmNDJiOWYwM2YwZjE4MWFkMWExMTkzNzA4YWI0NTYzOGE1ZjNkMzE4NWNiMDY2MmE1MzgyMzljYWNiZmM3ZGU3MTMxNWZlNjg2NDM4MmI0MmUzZWFhMjRlOWM=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
